AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy MozDef into AWS
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Settings'
      Parameters:
      - VpcId
      - PublicSubnetIds
    - Label:
        default: 'EC2 Instance'
      Parameters:
      - InstanceType
      - KeyName
      - AMIImageId
Parameters:
  S3TemplateLocation:
    Type: String
    Description: "The URL to the S3 bucket used to fetch the nested stack templates"
    Default: "https://s3-us-west-2.amazonaws.com/mozdef.infosec.mozilla.org/cf/"
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "The VPC ID of the VPC to deploy in"
    Default: "vpc-dc8eacb4"
  PublicSubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: "A comma delimited list of public subnet IDs"
    Default: "subnet-dd8eacb5,subnet-df8eacb7,subnet-de8eacb6"
  InstanceType:
    Type: String
    Default: "m5.large"
    Description: "EC2 instance type, e.g. m1.small, m1.large, etc."
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Name of an existing EC2 KeyPair to enable SSH access to the web server"
    Default: "infosec-pdx-workweek-2018"
  AMIImageId:
    Type: String
    Description: "The AMI Image ID to use of the EC2 instance"
    Default: "ami-0e6f50fa0c8c241af"
  ACMCertArn:
    Description: The ARN of your pre-issued ACM cert.
    Default : "arn:aws:acm:us-west-2:656532927350:certificate/79f641f2-4046-4754-a28f-4db80d7c0583"
    Type: String
    MinLength: "1"
  OIDCClientId:
    Description: "The client ID that your OIDC provider issues you for your Mozdef instance."
    Type: String
    Default: "lGsSlYNdiV6f5tF05pWN3EbQoDPHx44k"
  OIDCClientSecret:
    Type: String
    Description: "The secret that your OIDC provider issues you for your Mozdef instance."
    NoEcho: true
  OIDCDiscoveryURL:
    Type: String
    Default: "https://auth.mozilla.auth0.com/.well-known/openid-configuration"
    Description: "The URL of your OIDC provider's well-known discovery URL"
Resources:
  MozDefSecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: application
          Value: mozdef
      TemplateURL: !Join [ "", [ !Ref S3TemplateLocation, "mozdef-security-group.yml" ] ]
  MozDefIAMRoleAndInstanceProfile:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: application
          Value: mozdef
      TemplateURL: !Join [ "", [ !Ref S3TemplateLocation, "base-iam.yml" ] ]
  MozDefInstance:
    Type: AWS::CloudFormation::Stack
    DependsOn: [MozDefES]  # The user_data provisioning needs to wait until the ES index creation process completes
    Properties:
      Parameters:
        VpcId: !Ref VpcId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        IamInstanceProfile: !GetAtt MozDefIAMRoleAndInstanceProfile.Outputs.InstanceProfileArn
        AutoScaleGroupSubnetIds: !Join [ ",", !Ref PublicSubnetIds ]
        AMIImageId: !Ref AMIImageId
        MozDefSecurityGroupId: !GetAtt MozDefSecurityGroups.Outputs.MozDefSecurityGroupId
        MozDefLoadBalancerSecurityGroupId: !GetAtt MozDefSecurityGroups.Outputs.MozDefLoadBalancerSecurityGroupId
        MozDefACMCertArn: !Ref ACMCertArn
        ESURL: !GetAtt MozDefES.Outputs.ElasticsearchURL
        KibanaURL: !GetAtt MozDefES.Outputs.ElasticsearchKibanaURL
        AmazonMQHostName: !GetAtt MozDefMQ.Outputs.MQHostName
        AmazonMQScheme: !GetAtt MozDefMQ.Outputs.MQScheme
        AmazonMQPort: !GetAtt MozDefMQ.Outputs.MQPort
        AmazonMQUsername: !GetAtt MozDefMQ.Outputs.MQUser
        AmazonMQPassword: !GetAtt MozDefMQ.Outputs.MQPassword
        OIDCClientId: !Ref OIDCClientId
        OIDCClientSecret: !Ref OIDCClientSecret
        OIDCDiscoveryURL: !Ref OIDCDiscoveryURL
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref "AWS::StackName"
      TemplateURL: !Join [ "", [ !Ref S3TemplateLocation, "mozdef-instance.yml" ] ]
  MozDefES:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SubnetIds: !Join [ ",", !Ref PublicSubnetIds ]
        BlockStoreSizeGB: 100
        VpcId: !Ref VpcId
        MozDefInstanceSecurityGroup: !GetAtt MozDefSecurityGroups.Outputs.MozDefSecurityGroupId
        ESInstanceCount: 1
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref "AWS::StackName"
      TemplateURL: !Join [ "", [ !Ref S3TemplateLocation, "mozdef-es.yml" ] ]
  MozDefMQ:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        MQUserParameter: mozdef
        # MQPasswordParameter: we can leave this empty and it will autogenerate a password
        MQInstanceType: mq.t2.micro
        MQVpcId: !Ref VpcId
        MQSubnetIds: !Join [ ",", !Ref PublicSubnetIds ]
        MozDefSecurityGroup: !GetAtt MozDefSecurityGroups.Outputs.MozDefSecurityGroupId
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref "AWS::StackName"
      TemplateURL: !Join [ "", [ !Ref S3TemplateLocation, "mozdef-mq.yml" ] ]
  MozDefEFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCID0: !Ref VpcId
        Subnet: !Join [ ",", !Ref PublicSubnetIds ]
        MozDefSecurityGroup: !GetAtt MozDefSecurityGroups.Outputs.MozDefSecurityGroupId
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref "AWS::StackName"
      TemplateURL: !Join [ "", [ !Ref S3TemplateLocation, "mozdef-efs.yml" ] ]
