AWSTemplateFormatVersion: 2010-09-09
Description: SQS Queue that MozDef consumes events from
Resources:
  MozDefSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
      - Key: application
        Value: mozdef
      - Key: stack
        Value: !Ref AWS::StackName
  MozDefCloudTrailSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: AllowThisAccountSendToSQS
          Effect: Allow
          Principal:
            AWS: !Join [ '', [ 'arn:', 'aws:', 'iam::', !Ref 'AWS::AccountId', ':root' ] ]
          Action: sqs:SendMessage
          Resource: !GetAtt MozDefSQSQueue.Arn
      Queues:
        - !Ref MozDefSQSQueue
  MozDefSQSAlertTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
      - Key: application
        Value: mozdef
      - Key: stack
        Value: !Ref AWS::StackName
  MozDefAlertTaskSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: AllowThisAccountSendToSQS
          Effect: Allow
          Principal:
            AWS: !Join [ '', [ 'arn:', 'aws:', 'iam::', !Ref 'AWS::AccountId', ':root' ] ]
          Action: sqs:SendMessage
          Resource: !GetAtt MozDefSQSAlertTaskQueue.Arn
      Queues:
        - !Ref MozDefSQSAlertTaskQueue
Outputs:
  SQSQueueArn:
    Description: ARN of the SQS Queue that MozDef will consume events from
    Value: !GetAtt MozDefSQSQueue.Arn
  SQSQueueName:
    Description: Name of the SQS Queue that MozDef will consume events from
    Value: !GetAtt MozDefSQSQueue.QueueName
  SQSQueueUrl:
    Description: URL of the SQS Queue that MozDef will consume events from
    Value: !Ref MozDefSQSQueue
  AlertTaskSQSQueueArn:
    Description: ARN of the SQS Queue that MozDef will consume events from
    Value: !GetAtt MozDefSQSAlertTaskQueue.Arn
  AlertTaskSQSQueueName:
    Description: Name of the SQS Queue that MozDef will consume events from
    Value: !GetAtt MozDefSQSAlertTaskQueue.QueueName
  AlertTaskSQSQueueUrl:
    Description: The SQS queue url for the alerttask exchange as used in kombu.
    Value: !Ref MozDefSQSAlertTaskQueue
