AWSTemplateFormatVersion: '2010-09-09'
Description: Template to build out users for insecure account this is only used for training and testing.
Parameters:
  SNSReceiverArn:
    Type: String
    Description: The ARN of the SNS topic to post credentials to.  Note that this leaks credentials.
Resources:
  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  IAMUser1Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'IAMUser1'
  CaptureSetupData:
    Type: Custom::DataCapture
    Version: '1.0'
    Properties:
      ServiceToken: !Ref SNSReceiverArn
      AccessKey: !Ref 'IAMUser1Keys'
      SecretAccessKey: !GetAtt 'IAMUser1Keys.SecretAccessKey'
      lbURL: !GetAtt 'MyLoadBalancer.DNSName'
      AccountID: !Ref 'AWS::AccountId'
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        - !Select [ 0, 'Fn::GetAZs': !Ref 'AWS::Region' ]
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
Outputs:
  AccessKey:
    Description: AccessKey
    Value: !Ref 'IAMUser1Keys'
  SecretAccessKey:
    Description: SecretAccessKey
    Value: !GetAtt 'IAMUser1Keys.SecretAccessKey'
  LBUrl:
    Description: lburl
    Value: !GetAtt 'MyLoadBalancer.DNSName'
