AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Elastic File System
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: Must be the VPC Id of an existing Virtual Private Cloud.
  SubnetList:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select existing subnets.
  NumberOfSubnets:
    Type: String
    Description: Number of subnets in the Subnet parameter
  MozDefSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group of the Mozdef endpoint that is accessing EFS
Conditions:
   Has1Subnets: !Or [!Equals [!Ref NumberOfSubnets, 1], Condition: Has2Subnets]
   Has2Subnets: !Or [!Equals [!Ref NumberOfSubnets, 2], Condition: Has3Subnets]
   Has3Subnets: !Or [!Equals [!Ref NumberOfSubnets, 3], Condition: Has4Subnets]
   Has4Subnets: !Or [!Equals [!Ref NumberOfSubnets, 4], Condition: Has5Subnets]
   Has5Subnets: !Or [!Equals [!Ref NumberOfSubnets, 5], Condition: Has6Subnets]
   Has6Subnets: !Or [!Equals [!Ref NumberOfSubnets, 6], Condition: Has7Subnets]
   Has7Subnets: !Or [!Equals [!Ref NumberOfSubnets, 7], Condition: Has8Subnets]
   Has8Subnets: !Or [!Equals [!Ref NumberOfSubnets, 8], Condition: Has9Subnets]
   Has9Subnets: !Or [!Equals [!Ref NumberOfSubnets, 9], Condition: Has10Subnets]
   Has10Subnets: !Or [!Equals [!Ref NumberOfSubnets, 10], Condition: Has11Subnets]
   Has11Subnets: !Or [!Equals [!Ref NumberOfSubnets, 11], Condition: Has12Subnets]
   Has12Subnets: !Or [!Equals [!Ref NumberOfSubnets, 12], Condition: Has13Subnets]
   Has13Subnets: !Or [!Equals [!Ref NumberOfSubnets, 13], Condition: Has14Subnets]
   Has14Subnets: !Or [!Equals [!Ref NumberOfSubnets, 14], Condition: Has15Subnets]
   Has15Subnets: !Or [!Equals [!Ref NumberOfSubnets, 15], Condition: Has16Subnets]
   Has16Subnets: !Or [!Equals [!Ref NumberOfSubnets, 16], Condition: Has17Subnets]
   Has17Subnets: !Or [!Equals [!Ref NumberOfSubnets, 17], Condition: Has18Subnets]
   Has18Subnets: !Or [!Equals [!Ref NumberOfSubnets, 18], Condition: Has19Subnets]
   Has19Subnets: !Or [!Equals [!Ref NumberOfSubnets, 19], Condition: Has20Subnets]
   Has20Subnets: !Equals [!Ref NumberOfSubnets, 20]
Resources:
  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group of the MozDef EFS Mount Target
      SecurityGroupEgress:
      - IpProtocol: "-1"
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 2049
        ToPort: 2049
        SourceSecurityGroupId: !Ref MozDefSecurityGroup
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref AWS::StackName
      VpcId: !Ref VpcId
  ElasticFileSystem:
    Type: AWS::EFS::FileSystem
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Condition: Has1Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 0, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget2:
    Type: AWS::EFS::MountTarget
    Condition: Has2Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 1, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget3:
    Type: AWS::EFS::MountTarget
    Condition: Has3Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 2, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget4:
    Type: AWS::EFS::MountTarget
    Condition: Has4Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 3, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget5:
    Type: AWS::EFS::MountTarget
    Condition: Has5Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 4, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget6:
    Type: AWS::EFS::MountTarget
    Condition: Has6Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 5, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget7:
    Type: AWS::EFS::MountTarget
    Condition: Has7Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 6, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget8:
    Type: AWS::EFS::MountTarget
    Condition: Has8Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 7, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget9:
    Type: AWS::EFS::MountTarget
    Condition: Has9Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 8, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget10:
    Type: AWS::EFS::MountTarget
    Condition: Has10Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 9, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget11:
    Type: AWS::EFS::MountTarget
    Condition: Has11Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 10, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget12:
    Type: AWS::EFS::MountTarget
    Condition: Has12Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 11, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget13:
    Type: AWS::EFS::MountTarget
    Condition: Has13Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 12, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget14:
    Type: AWS::EFS::MountTarget
    Condition: Has14Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 13, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget15:
    Type: AWS::EFS::MountTarget
    Condition: Has15Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 14, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget16:
    Type: AWS::EFS::MountTarget
    Condition: Has16Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 15, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget17:
    Type: AWS::EFS::MountTarget
    Condition: Has17Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 16, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget18:
    Type: AWS::EFS::MountTarget
    Condition: Has18Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 17, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget19:
    Type: AWS::EFS::MountTarget
    Condition: Has19Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 18, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
  MountTarget20:
    Type: AWS::EFS::MountTarget
    Condition: Has20Subnets
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SubnetId: !Select [ 19, !Ref SubnetList ]
      SecurityGroups: [ !Ref MountTargetSecurityGroup ]
Outputs:
  EFSID:
    Description: Logical ID of the EFS Filesystem
    Value: !Ref ElasticFileSystem
