---
AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy IAM stuff for MozDef
Parameters:
Resources:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - "ec2.amazonaws.com"
          Action:
            - "sts:AssumeRole"
    ManagedPolicyArns:
      - String
    MaxSessionDuration: Integer
    Path: String
    Policies:
      - Policies
    RoleName: String
