#!/bin/bash

echo 'Welcome github webhook to the CodeBuild Job of MozDef.'
echo "It's dangerous to go alone.  Take one of these: <%%%%|==========>"

echo "Begin build / test of the MozDef codebase."

echo "But first a quick run of the test suite."
make tests
echo "Tests complete.  Now reasoning about the webhook event."

if [[ "branch/master" == "$CODEBUILD_WEBHOOK_TRIGGER" ]]
	then
		echo "Building a release from the edge of master branch."
        echo "C|_| This may take a bit.  Might as well grab a coffee."

elif [[ "$CODEBUILD_WEBHOOK_TRIGGER" =~ ^tag\/[0-9]\.[0-9]\.[0-9](\-(pre|testing))?$ ]]
	then
		echo "Building a release from a pre-release tag."
        echo "C|_| This may take a bit.  Might as well grab a coffee."

elif [[ "$CODEBUILD_WEBHOOK_TRIGGER" =~ ^tag\/[0-9]\.[0-9]\.[0-9](\-(prod))?$ ]]
	then
		echo "echo Building a production release from a tag."
        echo "C|_| This may take a bit.  Might as well grab a coffee."
        echo "Congrats on the release! --~~~=:>[XXXXXXXXX]>"
fi

echo "End build / test of the MozDef codebase."


