name: Tests
on:
  push:
    branches: '*'
  # Run every night
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build tests
      run: DOCKER_BUILDKIT=1 make build-tests

    - name: Run tests
      run: make run-tests
